allowBuilds:
  '@prisma/engines': true
  cypress: true
  esbuild: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - '@bernardsapida/web-ui@0.2.1 || 0.4.3 || 0.4.6 || 0.4.7 || 0.4.9 || 1.0.0 || 1.1.0'
