/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as TestRouteImport } from './routes/test'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as DevThemeRouteImport } from './routes/dev/theme'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests/index'
import { Route as AuthenticatedRequestsNewRouteImport } from './routes/_authenticated/requests/new'
import { Route as ApiAppConfigRouteImport } from './routes/api/app/config'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'
import { Route as ApiAuthDeleteAccountRouteImport } from './routes/api/auth/delete-account'
import { Route as ApiAuthUpdateProfileRouteImport } from './routes/api/auth/update-profile'
import { Route as ApiDevSeedRouteImport } from './routes/api/dev/seed'
import { Route as ApiDevToggleMaintenanceRouteImport } from './routes/api/dev/toggle-maintenance'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiPusherAuthRouteImport } from './routes/api/pusher/auth'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as AuthenticatedAdminCsmIndexRouteImport } from './routes/_authenticated/admin/csm/index'
import { Route as AuthenticatedAdminCsmCsmIdRouteImport } from './routes/_authenticated/admin/csm/$csmId'
import { Route as AuthenticatedRequestsRequestIdIndexRouteImport } from './routes/_authenticated/requests/$requestId/index'
import { Route as AuthenticatedRequestsRequestIdBudgetReviewRouteImport } from './routes/_authenticated/requests/$requestId/budget-review'
import { Route as AuthenticatedRequestsRequestIdCsmRouteImport } from './routes/_authenticated/requests/$requestId/csm'
import { Route as AuthenticatedRequestsRequestIdDirectorReviewRouteImport } from './routes/_authenticated/requests/$requestId/director-review'
import { Route as AuthenticatedRequestsRequestIdEditRouteImport } from './routes/_authenticated/requests/$requestId/edit'
import { Route as AuthenticatedRequestsRequestIdFinalDirectorApprovalRouteImport } from './routes/_authenticated/requests/$requestId/final-director-approval'
import { Route as AuthenticatedRequestsRequestIdFinalReviewRouteImport } from './routes/_authenticated/requests/$requestId/final-review'
import { Route as AuthenticatedRequestsRequestIdPdfRouteImport } from './routes/_authenticated/requests/$requestId/pdf'
import { Route as AuthenticatedRequestsRequestIdReviewRouteImport } from './routes/_authenticated/requests/$requestId/review'
import { Route as AuthenticatedRequestsPdfDemoRouteImport } from './routes/_authenticated/requests/pdf/demo'
import { Route as AuthenticatedStaffDashboardIndexRouteImport } from './routes/_authenticated/staff/dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const DevThemeRoute = DevThemeRouteImport.update({
  id: '/dev/theme',
  path: '/dev/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsNewRoute =
  AuthenticatedRequestsNewRouteImport.update({
    id: '/requests/new',
    path: '/requests/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAppConfigRoute = ApiAppConfigRouteImport.update({
  id: '/api/app/config',
  path: '/api/app/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDeleteAccountRoute = ApiAuthDeleteAccountRouteImport.update({
  id: '/api/auth/delete-account',
  path: '/api/auth/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUpdateProfileRoute = ApiAuthUpdateProfileRouteImport.update({
  id: '/api/auth/update-profile',
  path: '/api/auth/update-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSeedRoute = ApiDevSeedRouteImport.update({
  id: '/api/dev/seed',
  path: '/api/dev/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevToggleMaintenanceRoute = ApiDevToggleMaintenanceRouteImport.update({
  id: '/api/dev/toggle-maintenance',
  path: '/api/dev/toggle-maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPusherAuthRoute = ApiPusherAuthRouteImport.update({
  id: '/api/pusher/auth',
  path: '/api/pusher/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCsmIndexRoute =
  AuthenticatedAdminCsmIndexRouteImport.update({
    id: '/csm/',
    path: '/csm/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCsmCsmIdRoute =
  AuthenticatedAdminCsmCsmIdRouteImport.update({
    id: '/csm/$csmId',
    path: '/csm/$csmId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedRequestsRequestIdIndexRoute =
  AuthenticatedRequestsRequestIdIndexRouteImport.update({
    id: '/requests/$requestId/',
    path: '/requests/$requestId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsRequestIdBudgetReviewRoute =
  AuthenticatedRequestsRequestIdBudgetReviewRouteImport.update({
    id: '/requests/$requestId/budget-review',
    path: '/requests/$requestId/budget-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsRequestIdCsmRoute =
  AuthenticatedRequestsRequestIdCsmRouteImport.update({
    id: '/requests/$requestId/csm',
    path: '/requests/$requestId/csm',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsRequestIdDirectorReviewRoute =
  AuthenticatedRequestsRequestIdDirectorReviewRouteImport.update({
    id: '/requests/$requestId/director-review',
    path: '/requests/$requestId/director-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsRequestIdEditRoute =
  AuthenticatedRequestsRequestIdEditRouteImport.update({
    id: '/requests/$requestId/edit',
    path: '/requests/$requestId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsRequestIdFinalDirectorApprovalRoute =
  AuthenticatedRequestsRequestIdFinalDirectorApprovalRouteImport.update({
    id: '/requests/$requestId/final-director-approval',
    path: '/requests/$requestId/final-director-approval',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsRequestIdFinalReviewRoute =
  AuthenticatedRequestsRequestIdFinalReviewRouteImport.update({
    id: '/requests/$requestId/final-review',
    path: '/requests/$requestId/final-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsRequestIdPdfRoute =
  AuthenticatedRequestsRequestIdPdfRouteImport.update({
    id: '/requests/$requestId/pdf',
    path: '/requests/$requestId/pdf',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsRequestIdReviewRoute =
  AuthenticatedRequestsRequestIdReviewRouteImport.update({
    id: '/requests/$requestId/review',
    path: '/requests/$requestId/review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsPdfDemoRoute =
  AuthenticatedRequestsPdfDemoRouteImport.update({
    id: '/requests/pdf/demo',
    path: '/requests/pdf/demo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffDashboardIndexRoute =
  AuthenticatedStaffDashboardIndexRouteImport.update({
    id: '/staff/dashboard/',
    path: '/staff/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/test': typeof TestRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/posts': typeof ApiPostsRoute
  '/dev/theme': typeof DevThemeRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/api/app/config': typeof ApiAppConfigRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/delete-account': typeof ApiAuthDeleteAccountRoute
  '/api/auth/update-profile': typeof ApiAuthUpdateProfileRoute
  '/api/dev/seed': typeof ApiDevSeedRoute
  '/api/dev/toggle-maintenance': typeof ApiDevToggleMaintenanceRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/pusher/auth': typeof ApiPusherAuthRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/admin/csm/$csmId': typeof AuthenticatedAdminCsmCsmIdRoute
  '/requests/$requestId/budget-review': typeof AuthenticatedRequestsRequestIdBudgetReviewRoute
  '/requests/$requestId/csm': typeof AuthenticatedRequestsRequestIdCsmRoute
  '/requests/$requestId/director-review': typeof AuthenticatedRequestsRequestIdDirectorReviewRoute
  '/requests/$requestId/edit': typeof AuthenticatedRequestsRequestIdEditRoute
  '/requests/$requestId/final-director-approval': typeof AuthenticatedRequestsRequestIdFinalDirectorApprovalRoute
  '/requests/$requestId/final-review': typeof AuthenticatedRequestsRequestIdFinalReviewRoute
  '/requests/$requestId/pdf': typeof AuthenticatedRequestsRequestIdPdfRoute
  '/requests/$requestId/review': typeof AuthenticatedRequestsRequestIdReviewRoute
  '/requests/pdf/demo': typeof AuthenticatedRequestsPdfDemoRoute
  '/admin/csm/': typeof AuthenticatedAdminCsmIndexRoute
  '/requests/$requestId/': typeof AuthenticatedRequestsRequestIdIndexRoute
  '/staff/dashboard/': typeof AuthenticatedStaffDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/test': typeof TestRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/posts': typeof ApiPostsRoute
  '/dev/theme': typeof DevThemeRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/api/app/config': typeof ApiAppConfigRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/delete-account': typeof ApiAuthDeleteAccountRoute
  '/api/auth/update-profile': typeof ApiAuthUpdateProfileRoute
  '/api/dev/seed': typeof ApiDevSeedRoute
  '/api/dev/toggle-maintenance': typeof ApiDevToggleMaintenanceRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/pusher/auth': typeof ApiPusherAuthRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/admin/csm/$csmId': typeof AuthenticatedAdminCsmCsmIdRoute
  '/requests/$requestId/budget-review': typeof AuthenticatedRequestsRequestIdBudgetReviewRoute
  '/requests/$requestId/csm': typeof AuthenticatedRequestsRequestIdCsmRoute
  '/requests/$requestId/director-review': typeof AuthenticatedRequestsRequestIdDirectorReviewRoute
  '/requests/$requestId/edit': typeof AuthenticatedRequestsRequestIdEditRoute
  '/requests/$requestId/final-director-approval': typeof AuthenticatedRequestsRequestIdFinalDirectorApprovalRoute
  '/requests/$requestId/final-review': typeof AuthenticatedRequestsRequestIdFinalReviewRoute
  '/requests/$requestId/pdf': typeof AuthenticatedRequestsRequestIdPdfRoute
  '/requests/$requestId/review': typeof AuthenticatedRequestsRequestIdReviewRoute
  '/requests/pdf/demo': typeof AuthenticatedRequestsPdfDemoRoute
  '/admin/csm': typeof AuthenticatedAdminCsmIndexRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdIndexRoute
  '/staff/dashboard': typeof AuthenticatedStaffDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/test': typeof TestRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/posts': typeof ApiPostsRoute
  '/dev/theme': typeof DevThemeRoute
  '/_authenticated/requests/new': typeof AuthenticatedRequestsNewRoute
  '/api/app/config': typeof ApiAppConfigRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/delete-account': typeof ApiAuthDeleteAccountRoute
  '/api/auth/update-profile': typeof ApiAuthUpdateProfileRoute
  '/api/dev/seed': typeof ApiDevSeedRoute
  '/api/dev/toggle-maintenance': typeof ApiDevToggleMaintenanceRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/pusher/auth': typeof ApiPusherAuthRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/admin/csm/$csmId': typeof AuthenticatedAdminCsmCsmIdRoute
  '/_authenticated/requests/$requestId/budget-review': typeof AuthenticatedRequestsRequestIdBudgetReviewRoute
  '/_authenticated/requests/$requestId/csm': typeof AuthenticatedRequestsRequestIdCsmRoute
  '/_authenticated/requests/$requestId/director-review': typeof AuthenticatedRequestsRequestIdDirectorReviewRoute
  '/_authenticated/requests/$requestId/edit': typeof AuthenticatedRequestsRequestIdEditRoute
  '/_authenticated/requests/$requestId/final-director-approval': typeof AuthenticatedRequestsRequestIdFinalDirectorApprovalRoute
  '/_authenticated/requests/$requestId/final-review': typeof AuthenticatedRequestsRequestIdFinalReviewRoute
  '/_authenticated/requests/$requestId/pdf': typeof AuthenticatedRequestsRequestIdPdfRoute
  '/_authenticated/requests/$requestId/review': typeof AuthenticatedRequestsRequestIdReviewRoute
  '/_authenticated/requests/pdf/demo': typeof AuthenticatedRequestsPdfDemoRoute
  '/_authenticated/admin/csm/': typeof AuthenticatedAdminCsmIndexRoute
  '/_authenticated/requests/$requestId/': typeof AuthenticatedRequestsRequestIdIndexRoute
  '/_authenticated/staff/dashboard/': typeof AuthenticatedStaffDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/test'
    | '/unauthorized'
    | '/verify-email'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/api/posts'
    | '/dev/theme'
    | '/requests/new'
    | '/api/app/config'
    | '/api/auth/$'
    | '/api/auth/change-password'
    | '/api/auth/delete-account'
    | '/api/auth/update-profile'
    | '/api/dev/seed'
    | '/api/dev/toggle-maintenance'
    | '/api/files/$'
    | '/api/pusher/auth'
    | '/api/trpc/$'
    | '/admin/'
    | '/requests/'
    | '/admin/csm/$csmId'
    | '/requests/$requestId/budget-review'
    | '/requests/$requestId/csm'
    | '/requests/$requestId/director-review'
    | '/requests/$requestId/edit'
    | '/requests/$requestId/final-director-approval'
    | '/requests/$requestId/final-review'
    | '/requests/$requestId/pdf'
    | '/requests/$requestId/review'
    | '/requests/pdf/demo'
    | '/admin/csm/'
    | '/requests/$requestId/'
    | '/staff/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/test'
    | '/unauthorized'
    | '/verify-email'
    | '/dashboard'
    | '/profile'
    | '/api/posts'
    | '/dev/theme'
    | '/requests/new'
    | '/api/app/config'
    | '/api/auth/$'
    | '/api/auth/change-password'
    | '/api/auth/delete-account'
    | '/api/auth/update-profile'
    | '/api/dev/seed'
    | '/api/dev/toggle-maintenance'
    | '/api/files/$'
    | '/api/pusher/auth'
    | '/api/trpc/$'
    | '/admin'
    | '/requests'
    | '/admin/csm/$csmId'
    | '/requests/$requestId/budget-review'
    | '/requests/$requestId/csm'
    | '/requests/$requestId/director-review'
    | '/requests/$requestId/edit'
    | '/requests/$requestId/final-director-approval'
    | '/requests/$requestId/final-review'
    | '/requests/$requestId/pdf'
    | '/requests/$requestId/review'
    | '/requests/pdf/demo'
    | '/admin/csm'
    | '/requests/$requestId'
    | '/staff/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/test'
    | '/unauthorized'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/api/posts'
    | '/dev/theme'
    | '/_authenticated/requests/new'
    | '/api/app/config'
    | '/api/auth/$'
    | '/api/auth/change-password'
    | '/api/auth/delete-account'
    | '/api/auth/update-profile'
    | '/api/dev/seed'
    | '/api/dev/toggle-maintenance'
    | '/api/files/$'
    | '/api/pusher/auth'
    | '/api/trpc/$'
    | '/_authenticated/admin/'
    | '/_authenticated/requests/'
    | '/_authenticated/admin/csm/$csmId'
    | '/_authenticated/requests/$requestId/budget-review'
    | '/_authenticated/requests/$requestId/csm'
    | '/_authenticated/requests/$requestId/director-review'
    | '/_authenticated/requests/$requestId/edit'
    | '/_authenticated/requests/$requestId/final-director-approval'
    | '/_authenticated/requests/$requestId/final-review'
    | '/_authenticated/requests/$requestId/pdf'
    | '/_authenticated/requests/$requestId/review'
    | '/_authenticated/requests/pdf/demo'
    | '/_authenticated/admin/csm/'
    | '/_authenticated/requests/$requestId/'
    | '/_authenticated/staff/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TestRoute: typeof TestRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiPostsRoute: typeof ApiPostsRoute
  DevThemeRoute: typeof DevThemeRoute
  ApiAppConfigRoute: typeof ApiAppConfigRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthDeleteAccountRoute: typeof ApiAuthDeleteAccountRoute
  ApiAuthUpdateProfileRoute: typeof ApiAuthUpdateProfileRoute
  ApiDevSeedRoute: typeof ApiDevSeedRoute
  ApiDevToggleMaintenanceRoute: typeof ApiDevToggleMaintenanceRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiPusherAuthRoute: typeof ApiPusherAuthRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/theme': {
      id: '/dev/theme'
      path: '/dev/theme'
      fullPath: '/dev/theme'
      preLoaderRoute: typeof DevThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/new': {
      id: '/_authenticated/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthenticatedRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/app/config': {
      id: '/api/app/config'
      path: '/api/app/config'
      fullPath: '/api/app/config'
      preLoaderRoute: typeof ApiAppConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/delete-account': {
      id: '/api/auth/delete-account'
      path: '/api/auth/delete-account'
      fullPath: '/api/auth/delete-account'
      preLoaderRoute: typeof ApiAuthDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/update-profile': {
      id: '/api/auth/update-profile'
      path: '/api/auth/update-profile'
      fullPath: '/api/auth/update-profile'
      preLoaderRoute: typeof ApiAuthUpdateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/seed': {
      id: '/api/dev/seed'
      path: '/api/dev/seed'
      fullPath: '/api/dev/seed'
      preLoaderRoute: typeof ApiDevSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/toggle-maintenance': {
      id: '/api/dev/toggle-maintenance'
      path: '/api/dev/toggle-maintenance'
      fullPath: '/api/dev/toggle-maintenance'
      preLoaderRoute: typeof ApiDevToggleMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pusher/auth': {
      id: '/api/pusher/auth'
      path: '/api/pusher/auth'
      fullPath: '/api/pusher/auth'
      preLoaderRoute: typeof ApiPusherAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/csm/': {
      id: '/_authenticated/admin/csm/'
      path: '/csm'
      fullPath: '/admin/csm/'
      preLoaderRoute: typeof AuthenticatedAdminCsmIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/csm/$csmId': {
      id: '/_authenticated/admin/csm/$csmId'
      path: '/csm/$csmId'
      fullPath: '/admin/csm/$csmId'
      preLoaderRoute: typeof AuthenticatedAdminCsmCsmIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/requests/$requestId/': {
      id: '/_authenticated/requests/$requestId/'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId/'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$requestId/budget-review': {
      id: '/_authenticated/requests/$requestId/budget-review'
      path: '/requests/$requestId/budget-review'
      fullPath: '/requests/$requestId/budget-review'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdBudgetReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$requestId/csm': {
      id: '/_authenticated/requests/$requestId/csm'
      path: '/requests/$requestId/csm'
      fullPath: '/requests/$requestId/csm'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdCsmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$requestId/director-review': {
      id: '/_authenticated/requests/$requestId/director-review'
      path: '/requests/$requestId/director-review'
      fullPath: '/requests/$requestId/director-review'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdDirectorReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$requestId/edit': {
      id: '/_authenticated/requests/$requestId/edit'
      path: '/requests/$requestId/edit'
      fullPath: '/requests/$requestId/edit'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$requestId/final-director-approval': {
      id: '/_authenticated/requests/$requestId/final-director-approval'
      path: '/requests/$requestId/final-director-approval'
      fullPath: '/requests/$requestId/final-director-approval'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdFinalDirectorApprovalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$requestId/final-review': {
      id: '/_authenticated/requests/$requestId/final-review'
      path: '/requests/$requestId/final-review'
      fullPath: '/requests/$requestId/final-review'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdFinalReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$requestId/pdf': {
      id: '/_authenticated/requests/$requestId/pdf'
      path: '/requests/$requestId/pdf'
      fullPath: '/requests/$requestId/pdf'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdPdfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$requestId/review': {
      id: '/_authenticated/requests/$requestId/review'
      path: '/requests/$requestId/review'
      fullPath: '/requests/$requestId/review'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/pdf/demo': {
      id: '/_authenticated/requests/pdf/demo'
      path: '/requests/pdf/demo'
      fullPath: '/requests/pdf/demo'
      preLoaderRoute: typeof AuthenticatedRequestsPdfDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/dashboard/': {
      id: '/_authenticated/staff/dashboard/'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard/'
      preLoaderRoute: typeof AuthenticatedStaffDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCsmCsmIdRoute: typeof AuthenticatedAdminCsmCsmIdRoute
  AuthenticatedAdminCsmIndexRoute: typeof AuthenticatedAdminCsmIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCsmCsmIdRoute: AuthenticatedAdminCsmCsmIdRoute,
  AuthenticatedAdminCsmIndexRoute: AuthenticatedAdminCsmIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRequestsNewRoute: typeof AuthenticatedRequestsNewRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
  AuthenticatedRequestsRequestIdBudgetReviewRoute: typeof AuthenticatedRequestsRequestIdBudgetReviewRoute
  AuthenticatedRequestsRequestIdCsmRoute: typeof AuthenticatedRequestsRequestIdCsmRoute
  AuthenticatedRequestsRequestIdDirectorReviewRoute: typeof AuthenticatedRequestsRequestIdDirectorReviewRoute
  AuthenticatedRequestsRequestIdEditRoute: typeof AuthenticatedRequestsRequestIdEditRoute
  AuthenticatedRequestsRequestIdFinalDirectorApprovalRoute: typeof AuthenticatedRequestsRequestIdFinalDirectorApprovalRoute
  AuthenticatedRequestsRequestIdFinalReviewRoute: typeof AuthenticatedRequestsRequestIdFinalReviewRoute
  AuthenticatedRequestsRequestIdPdfRoute: typeof AuthenticatedRequestsRequestIdPdfRoute
  AuthenticatedRequestsRequestIdReviewRoute: typeof AuthenticatedRequestsRequestIdReviewRoute
  AuthenticatedRequestsPdfDemoRoute: typeof AuthenticatedRequestsPdfDemoRoute
  AuthenticatedRequestsRequestIdIndexRoute: typeof AuthenticatedRequestsRequestIdIndexRoute
  AuthenticatedStaffDashboardIndexRoute: typeof AuthenticatedStaffDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRequestsNewRoute: AuthenticatedRequestsNewRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
  AuthenticatedRequestsRequestIdBudgetReviewRoute:
    AuthenticatedRequestsRequestIdBudgetReviewRoute,
  AuthenticatedRequestsRequestIdCsmRoute:
    AuthenticatedRequestsRequestIdCsmRoute,
  AuthenticatedRequestsRequestIdDirectorReviewRoute:
    AuthenticatedRequestsRequestIdDirectorReviewRoute,
  AuthenticatedRequestsRequestIdEditRoute:
    AuthenticatedRequestsRequestIdEditRoute,
  AuthenticatedRequestsRequestIdFinalDirectorApprovalRoute:
    AuthenticatedRequestsRequestIdFinalDirectorApprovalRoute,
  AuthenticatedRequestsRequestIdFinalReviewRoute:
    AuthenticatedRequestsRequestIdFinalReviewRoute,
  AuthenticatedRequestsRequestIdPdfRoute:
    AuthenticatedRequestsRequestIdPdfRoute,
  AuthenticatedRequestsRequestIdReviewRoute:
    AuthenticatedRequestsRequestIdReviewRoute,
  AuthenticatedRequestsPdfDemoRoute: AuthenticatedRequestsPdfDemoRoute,
  AuthenticatedRequestsRequestIdIndexRoute:
    AuthenticatedRequestsRequestIdIndexRoute,
  AuthenticatedStaffDashboardIndexRoute: AuthenticatedStaffDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TestRoute: TestRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiPostsRoute: ApiPostsRoute,
  DevThemeRoute: DevThemeRoute,
  ApiAppConfigRoute: ApiAppConfigRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthDeleteAccountRoute: ApiAuthDeleteAccountRoute,
  ApiAuthUpdateProfileRoute: ApiAuthUpdateProfileRoute,
  ApiDevSeedRoute: ApiDevSeedRoute,
  ApiDevToggleMaintenanceRoute: ApiDevToggleMaintenanceRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiPusherAuthRoute: ApiPusherAuthRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
