/**
 * The measurement. This is the part of the slice that is worth anything.
 *
 * A palette is not "accessible" because it was generated by code that intended
 * it to be. It is accessible if the values IN THE SHIPPED STYLESHEET, converted
 * to the pixels a browser will actually paint, clear their bar. So this suite
 * deliberately does not import the generator's output: it parses
 * `src/styles/palettes.css` and `src/styles.css` off disk, exactly as Vite will
 * hand them to the browser, and measures those.
 *
 * That distinction is the entire point. A generator that is right and a
 * stylesheet that was never regenerated pass together in any test that reads
 * the generator. They cannot both pass here.
 *
 * Four things are checked, in order of how expensive they were to learn:
 *
 * 1. EVERY PAIRING, EVERY PRESET, BOTH THEMES. Sixteen palettes' worth, not one
 *    - contrast at a fixed oklch lightness varies with hue, so amber passing is
 *      no evidence at all about emerald.
 * 2. EVERY VALUE IS IN GAMUT. An oklch chroma above what sRGB can paint is
 *    silently remapped by the browser, and the colour measured then stops being
 *    the colour painted. A ratio computed from an out-of-gamut token is fiction
 *    dressed as a number.
 * 3. THE TOKENS THE PAIRINGS NAME ACTUALLY EXIST. A renamed token resolves to
 *    nothing, the row is skipped, and a shrinking report looks like a passing
 *    one. So the row count is asserted, not just the rows.
 * 4. THE TWO BRAND RAMPS ARE STILL TWO. They answer to opposite obligations -
 *    ink on the fill, page behind the words - and collapsing them back into one
 *    is the regression that put the wordmark at 1.4:1 on a dark page.
 */

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { contrastOfRgb, isInGamut, oklchToHex, oklchToRgb, parseOklch, type Rgb, reportRatio } from "./oklch";
import { SURFACE_NAMES } from "./options";
import { measurePairings, PAIRINGS } from "./pairings";
import type { SurfaceStrategy } from "./palette.build";
import { AA_TEXT, AAA_TEXT, NON_TEXT } from "./palette.build";
import { PALETTE_PRESETS, type PalettePreset } from "./presets";
import { collisionFor, SEMANTIC_HUES } from "./purposes";

const here = dirname(fileURLToPath(import.meta.url));
const srcRoot = resolve(here, "../..");

const paletteSheet = readFileSync(resolve(srcRoot, "styles/palettes.css"), "utf8");
// styles/brand.css, not styles.css: the raw values this file measures - :root,
// .dark and the font stacks - moved there when the package took the @theme block
// and the component rules. styles.css is now imports and this project's @font-face.
const baseSheet = readFileSync(resolve(srcRoot, "styles/brand.css"), "utf8");

/**
 * Pull one selector's declarations out of a stylesheet.
 *
 * A regex rather than a CSS parser, and that is a deliberate limit rather than
 * laziness: it only has to read a generated file whose shape this repo controls,
 * and a dependency here would be a dependency the measurement itself rests on.
 * If it ever fails to find a block the tests fail loudly on an empty map rather
 * than quietly measuring nothing - see the row-count assertion.
 */
function declarationsFor(sheet: string, selector: string): Record<string, string> {
	const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
	const block = new RegExp(`${escaped}\\s*\\{([^}]*)\\}`).exec(sheet);
	if (!block) return {};

	const declarations: Record<string, string> = {};
	for (const line of block[1].split(";")) {
		const [name, ...rest] = line.split(":");
		if (!name?.trim().startsWith("--")) continue;
		declarations[name.trim()] = rest.join(":").trim();
	}

	return declarations;
}

/**
 * Everything in scope for one palette, theme and surface strategy - layered the
 * way the cascade layers it.
 *
 * The surface block goes on LAST in light and is absent entirely in dark, which
 * mirrors its `:root:not(.dark)` selector rather than restating it. Getting this
 * order wrong in the test would hide the exact bug the selector exists to stop:
 * the block outranks `.dark[data-palette]` on specificity, so an unguarded
 * version repaints a dark page white.
 */
function tokensFor(
	palette: string,
	theme: "dark" | "light",
	surface: SurfaceStrategy = "flat",
): Record<string, string> {
	const light = declarationsFor(paletteSheet, `:root[data-palette="${palette}"]`);
	const dark = theme === "dark" ? declarationsFor(paletteSheet, `.dark[data-palette="${palette}"]`) : {};
	const raised =
		theme === "light" && surface !== "flat"
			? declarationsFor(paletteSheet, `:root:not(.dark)[data-palette="${palette}"][data-surface="${surface}"]`)
			: {};

	// styles.css last: it holds what the palette does NOT own, and nothing in it
	// may shadow a generated token. Spread order is checked by the duplicate test
	// below rather than assumed here.
	return { ...declarationsFor(baseSheet, ":root"), ...light, ...dark, ...raised };
}

function resolverFor(tokens: Record<string, string>): (token: string) => Rgb | null {
	return (token) => {
		const value = tokens[token];
		if (value === undefined) return null;

		const color = parseOklch(value);
		return color === null ? null : oklchToRgb(color);
	};
}

/**
 * Every palette, in both themes, under every surface strategy.
 *
 * `raised` is in here rather than trusted because it re-solves three brand inks
 * against a page that is no longer pure white. Those tokens are the reason the
 * strategy emits anything beyond a background at all, and an unmeasured
 * re-solve is exactly the thing this file exists to refuse.
 */
/**
 * SOLVED presets only.
 *
 * A palette carrying `supplied` is a designer's, and it answers to a different
 * contract: those values ship verbatim and may fail, because the alternative is
 * a build step editing somebody's brand. Holding them to the guarantee here
 * would leave two bad options - refuse the palette, or weaken the bar for the
 * solved ones - so they are measured separately, below, against what they do
 * promise: that what shipped is what was handed over.
 */
// Widened to the interface: PALETTE_PRESETS is `as const`, so an entry without
// `supplied` has a literal type that does not know the key exists at all.
const ALL: readonly PalettePreset[] = PALETTE_PRESETS;
const SOLVED = ALL.filter((preset) => !preset.supplied);
const DESIGNER = ALL.filter((preset) => preset.supplied);

const CASES = SOLVED.flatMap((preset) =>
	(["light", "dark"] as const).flatMap((theme) => SURFACE_NAMES.map((surface) => ({ preset, surface, theme }))),
);

describe("the shipped palettes", () => {
	describe.each(CASES)("$preset.name / $theme / $surface", ({ preset, surface, theme }) => {
		const tokens = tokensFor(preset.name, theme, surface);
		const rows = measurePairings(resolverFor(tokens));

		it("resolves every token the report names", () => {
			// The failure this closes: a token is renamed, its rows silently vanish,
			// and a report of four green rows looks better than one of fourteen.
			const missing = PAIRINGS.filter((pairing) => !tokens[pairing.foreground] || !tokens[pairing.background]);

			expect(
				missing.map((pairing) => pairing.id),
				`unresolved: ${missing.map((p) => p.id).join(", ")}`,
			).toEqual([]);
			expect(rows).toHaveLength(PAIRINGS.length);
		});

		it("keeps every text pairing at AAA", () => {
			for (const row of rows.filter((candidate) => candidate.kind === "text")) {
				expect(
					row.ratio,
					`${row.id} (${row.foregroundHex} on ${row.backgroundHex}) is ${row.ratio}:1`,
				).toBeGreaterThanOrEqual(AAA_TEXT);
				expect(row.aa, `${row.id} clears AA`).toBe(true);
				expect(row.aaa, `${row.id} clears AAA`).toBe(true);
			}
		});

		it("keeps every non-text pairing above the 3:1 identifiability bar", () => {
			for (const row of rows.filter((candidate) => candidate.kind === "non-text" && !candidate.accepted)) {
				expect(
					row.ratio,
					`${row.id} (${row.foregroundHex} on ${row.backgroundHex}) is ${row.ratio}:1`,
				).toBeGreaterThanOrEqual(NON_TEXT);
			}
		});

		it("pins the accepted exceptions so a decision cannot drift into an accident", () => {
			// A row carrying `accepted` is below its bar ON PURPOSE, and the reason
			// is recorded on the pairing itself. It is still asserted, just against
			// where it stands rather than against the bar: if somebody later changes
			// a lightness and this slides further, that is a new regression rather
			// than the trade that was signed off, and it fails here.
			for (const row of rows.filter((candidate) => candidate.accepted)) {
				// The floor travels with the row rather than living here. Two exceptions
				// were accepted at very different ratios, and one shared number would
				// have to be the lower of them - which would silently stop pinning the
				// other, the exact drift this test exists to catch.
				expect(row.acceptedFloor, `${row.id} declares the floor it was accepted at`).toBeTypeOf("number");
				expect(row.ratio, `${row.id} is ${row.ratio}:1 and was accepted at ${row.acceptedFloor}:1`).toBeGreaterThan(
					row.acceptedFloor as number,
				);
				expect(row.accepted, `${row.id} records WHY it is accepted`).toBeTruthy();
			}
		});

		it("keeps the brand fill and the brand ink as two separate ramps", () => {
			// Same lightness band by necessity - both are pinned near the same bar -
			// but they must not be literally the same declaration, or a change to
			// --background stops moving the wordmark and nothing says so.
			expect(tokens["--gradient-brand-from"]).toBeDefined();
			expect(tokens["--gradient-brand-ink-from"]).toBeDefined();
			expect(tokens["--gradient-brand"]).toContain("--gradient-brand-from");
			expect(tokens["--gradient-brand-ink"]).toContain("--gradient-brand-ink-from");
		});
	});

	it.each([
		["styles/brand.css", baseSheet],
		["styles/palettes.css", paletteSheet],
	])("paints every oklch value %s authored, with no silent gamut mapping", (_name, sheet) => {
		// A whole-file scan rather than a per-token one, because the trap is not
		// confined to custom properties: the chip tones, the toast shadow and the
		// status rails are all literals in ordinary rules, and twelve of them were
		// over the ceiling when this test was written. Nothing looked wrong,
		// because nothing does - the browser quietly maps them and paints a colour
		// nobody authored. What breaks is the MEASUREMENT: every ratio computed
		// from those values described a colour that was never on screen.
		const literals = sheet.matchAll(/oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.-]+)/g);
		const outside = new Set<string>();

		for (const [full, l, c, h] of literals) {
			if (!isInGamut({ c: Number(c), h: Number(h), l: Number(l) })) outside.add(full);
		}

		expect([...outside], `out of sRGB gamut:\n${[...outside].join("\n")}`).toEqual([]);
	});

	it("carries every solved preset in the stylesheet", () => {
		for (const preset of PALETTE_PRESETS) {
			expect(paletteSheet, `${preset.name} has a light block`).toContain(`:root[data-palette="${preset.name}"]`);
			expect(paletteSheet, `${preset.name} has a dark block`).toContain(`.dark[data-palette="${preset.name}"]`);
		}
	});

	/*
	 * The bug this pins: `:root[data-palette=X][data-surface=Y]` is (0,3,0) and
	 * `.dark[data-palette=X]` is (0,2,0). Both match <html>. An unguarded surface
	 * block therefore wins in DARK mode too and repaints a near-black page white.
	 * The `:not(.dark)` in the emitted selector is what stops it, and this is the
	 * assertion that notices if somebody simplifies the selector.
	 */
	it("scopes every surface block to light mode, so it cannot outrank the dark theme", () => {
		const blocks = paletteSheet.split("\n").filter((line) => line.includes("[data-surface=") && line.includes("{"));

		expect(blocks.length).toBeGreaterThan(0);
		for (const selector of blocks) {
			expect(selector).toContain(":not(.dark)");
		}
	});

	/*
	 * SEMANTIC_HUES is hard-coded in purposes.ts because the picker needs it at
	 * render time and styles.css is not importable. Hard-coding without this
	 * check is how a guard quietly stops guarding: move --warning and the
	 * collision warning keeps pointing at where it used to be.
	 */
	it("keeps SEMANTIC_HUES in step with the hues styles.css actually ships", () => {
		// Everything before `.dark {` is the light theme. Not declarationsFor: its
		// `[^}]*` stops at the first closing brace, which lands well above the
		// status tokens in a `:root` block this long.
		const darkAt = baseSheet.indexOf("\n.dark {");
		expect(darkAt, "the .dark block is where this expects it").toBeGreaterThan(0);
		const lightHalf = baseSheet.slice(0, darkAt);

		for (const [role, hue] of Object.entries(SEMANTIC_HUES)) {
			const match = new RegExp(String.raw`--${role}:\s*(oklch\([^)]*\))`).exec(lightHalf);
			const declared = match ? parseOklch(match[1]) : null;

			expect(declared, `--${role} resolves in styles.css`).not.toBeNull();
			expect(declared?.h, `--${role} is at hue ${hue}, as purposes.ts assumes`).toBe(hue);
		}
	});

	/*
	 * Not an aesthetic assertion - it pins the three the customizer WARNS about,
	 * so that a hue change which quietly creates or removes a collision has to be
	 * acknowledged here. rose/danger at 10, amber/warning at 3 and
	 * emerald/success at 5 are all shipped on purpose.
	 */
	it("knows which shipped presets crowd a semantic hue", () => {
		const colliding = PALETTE_PRESETS.filter((preset) => collisionFor(preset.accentHue)).map((preset) => preset.name);

		/*
		 * Five, and every one of them ships that way in real life: Netflix and
		 * Airbnb sit on --danger, Rabbit beside it, Spotify and revolve on
		 * --success. That is what a real brand palette looks like, and the warning
		 * exists to say so rather than to prevent it.
		 *
		 * `revolve` is the newest and the closest - hue 162 against --success at
		 * 160, two degrees. This test failing is the mechanism working: the list is
		 * pinned precisely so a hue change that creates a collision has to be
		 * acknowledged here rather than noticed later on a screen where the brand
		 * button and the success toast are the same green.
		 */
		expect(colliding.sort()).toEqual(["airbnb", "irms", "netflix", "rabbit", "revolve", "spotify"]);
	});

	/*
	 * The one HeroUI colour token that does not follow a theme unless we make it.
	 * It is `-webkit-text-fill-color` and `caret-color` on every input, and
	 * HeroUI freezes it to a near-black literal - fine on a light ground, and
	 * unreadable on a dark one, which is exactly what a supplied palette can be.
	 */
	it("makes the text you type follow the palette rather than HeroUI's literal", () => {
		const darkAt = baseSheet.indexOf("\n.dark {");
		const lightHalf = baseSheet.slice(0, darkAt);
		const darkHalf = baseSheet.slice(darkAt);

		for (const [themeName, half] of [
			["light", lightHalf],
			["dark", darkHalf],
		] as const) {
			const match = /--field-foreground:\s*([^;]+);/.exec(half);
			expect(match, `${themeName} declares --field-foreground`).not.toBeNull();
			expect(match?.[1].trim(), `${themeName} points it at the palette`).toBe("var(--foreground)");
		}
	});

	it("leaves no palette-owned token declared in styles.css", () => {
		// The trap this closes is subtle: `:root` and `[data-palette=…]` would tie
		// on specificity, so a leftover brand declaration in styles.css does not
		// obviously break anything - it just wins or loses depending on import
		// order, and only for one token, and only in one theme.
		const base = declarationsFor(baseSheet, ":root");
		const generated = Object.keys(declarationsFor(paletteSheet, ':root[data-palette="sky"]'));
		const overlap = generated.filter((token) => token in base);

		expect(overlap, `declared in both sheets: ${overlap.join(", ")}`).toEqual([]);
	});

	it("holds --brand-primary and --brand-pale apart", () => {
		// The token swatch grid asserts these render as distinct colours. Steps
		// that collapse into one another are a broken scale that passes every "does
		// it resolve" check ever written.
		//
		// Two steps, not the four this used to check: --brand-deep and
		// --brand-bright were removed, because the brand is one colour plus the pale
		// ground it is tinted against. The assertion is weaker for an honest reason
		// - there are fewer things left that can collide - and it is still the one
		// that catches a generator change flattening the fill into the tint.
		for (const preset of PALETTE_PRESETS) {
			for (const theme of ["light", "dark"] as const) {
				const tokens = tokensFor(preset.name, theme);
				const steps = ["--brand-primary", "--brand-pale"].map((token) => tokens[token]);

				expect(new Set(steps).size, `${preset.name}/${theme}: ${steps.join(", ")}`).toBe(steps.length);
			}
		}
	});
});

/* -------------------------------------------------------------------------- */

/**
 * The brand ramp, measured out of the shipped sheet like everything else here.
 *
 * EVERY palette, designer ones included - unlike the pairing suite above, which
 * exempts them. The exemption there is about a supplied hex being allowed to
 * fail a contrast bar, and none of the four things asserted below is a contrast
 * bar. The ramp's contract is ordering, gamut, and 500 being the brand, and a
 * designer palette is held to all three exactly like a solved one.
 *
 * Nothing in the package reads these tokens, so the ordinary safety net - a
 * component looking wrong - does not exist for them. This suite IS the net.
 */
const RAMP_STEP_LIST = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;

/**
 * The palettes whose brand sits too near an endpoint to anchor the ramp on, so
 * they ship the canonical curve instead. See `RAMP_MIN_SPAN` in palette.build.ts.
 *
 * One, and it is a designer's: `revolve`'s brand is a near-black green at L
 * 0.2949 against the 950 step's 0.282. Every solved preset clears the bar
 * comfortably - this is what a real brand deck does that a generated hue does
 * not, which is exactly why the fallback exists.
 */
const RAMP_FALLBACKS: string[] = ["revolve"];

describe.each(ALL)("the brand ramp - $name", (preset) => {
	const light = declarationsFor(paletteSheet, `:root[data-palette="${preset.name}"]`);
	const dark = declarationsFor(paletteSheet, `.dark[data-palette="${preset.name}"]`);
	const step = (value: (typeof RAMP_STEP_LIST)[number]) => parseOklch(light[`--brand-${value}`] ?? "");

	it("ships all eleven steps", () => {
		// The row-count failure this file already guards for pairings: a step that
		// silently stops being emitted resolves to nothing, and `bg-app-brand-300`
		// then paints no background at all rather than erroring.
		const missing = RAMP_STEP_LIST.filter((value) => step(value) === null);
		expect(missing, `unresolved: ${missing.join(", ")}`).toEqual([]);
	});

	it("runs strictly lightest to darkest, which is the whole contract", () => {
		// `50` means the lightest step because that is what it means in stock
		// Tailwind, and a designer reading a Figma file is going to assume it. A
		// ramp that is merely eleven colours is not a scale.
		const lightnesses = RAMP_STEP_LIST.map((value) => step(value)?.l ?? Number.NaN);

		for (const [index, value] of RAMP_STEP_LIST.slice(1).entries()) {
			expect(
				lightnesses[index + 1],
				`${value} (L ${lightnesses[index + 1]}) must be darker than ${RAMP_STEP_LIST[index]} (L ${lightnesses[index]})`,
			).toBeLessThan(lightnesses[index]);
		}
	});

	it("puts the brand itself at 500, or says why it could not", () => {
		/*
		 * The reason the lightness curve is warped through the anchor rather than
		 * the anchor being snapped onto the nearest canonical step. On a designer
		 * palette this is the hex that was handed over, so `bg-app-brand-500` and
		 * `bg-app-brand` have to paint the same pixel or the scale is lying about
		 * what it is a scale OF.
		 *
		 * RAMP_FALLBACKS is pinned rather than computed, on the same grounds as the
		 * semantic-hue collision list below: a brand moving close enough to an
		 * endpoint to lose its anchor is a real change in what the ramp promises,
		 * and it should have to be acknowledged here rather than noticed later.
		 */
		if (RAMP_FALLBACKS.includes(preset.name)) {
			// The unwarped curve, so at least the scale is the canonical one.
			expect(step(500)?.l, `${preset.name} fell back and sits on the canonical 500`).toBeCloseTo(0.623, 3);
			return;
		}

		expect(light["--brand-500"]).toBe(light["--gradient-brand-via"]);
	});

	it("does not invert in dark, so a step means one lightness in both themes", () => {
		/*
		 * The rule the whole design rests on, and the one a future change is most
		 * likely to break by "fixing" it: every OTHER brand token here flips
		 * between themes, so redeclaring the ramp in the dark block looks like
		 * consistency. It is the opposite - `text-app-brand-900` on
		 * `bg-app-brand-50` would become dark-on-dark on a theme toggle.
		 *
		 * Asserted on the dark block having no step at all, rather than on the
		 * values matching, because inheritance is the mechanism: a redeclaration
		 * that happens to be identical today is one edit away from not being.
		 */
		const redeclared = RAMP_STEP_LIST.filter((value) => `--brand-${value}` in dark);
		expect(redeclared, `the dark block redeclares: ${redeclared.join(", ")}`).toEqual([]);
	});
});

/**
 * The pairing table the Design tokens lab publishes, held to the numbers it was
 * measured at.
 *
 * tokens.css says outright that the ramp carries no contrast guarantee, and that
 * stays true - these are not a promise about the scale, they are the specific
 * combinations somebody checked, so "at your own risk" has a shortlist attached
 * rather than being a shrug. The floors are the WORST case across all nine
 * palettes at the time of writing; a hue change that erodes one fails here
 * instead of on a screen.
 */
describe("the brand ramp's measured pairings", () => {
	const ramp = (palette: string, value: number) => {
		const color = parseOklch(
			declarationsFor(paletteSheet, `:root[data-palette="${palette}"]`)[`--brand-${value}`] ?? "",
		);
		return color ? oklchToRgb(color) : null;
	};
	const WHITE: Rgb = { b: 255, g: 255, r: 255 };

	it.each(ALL)("keeps deep-on-pale readable as body text - $name", (preset) => {
		// 800 and darker on 200 and paler. 700 is NOT on this list: it measures
		// 4.43:1 on `50` at its worst hue, which is a fail, while clearing 4.8 on
		// white - exactly the kind of near miss that gets waved through by eye.
		for (const foreground of [800, 900, 950]) {
			for (const background of [50, 100, 200]) {
				const ratio = reportRatio(contrastOfRgb(ramp(preset.name, foreground)!, ramp(preset.name, background)!));
				expect(ratio, `${foreground} on ${background}`).toBeGreaterThanOrEqual(AA_TEXT);
			}
		}
	});

	it.each(ALL)("keeps white readable on the deep end - $name", (preset) => {
		for (const background of [800, 900, 950]) {
			const ratio = reportRatio(contrastOfRgb(WHITE, ramp(preset.name, background)!));
			expect(ratio, `white on ${background}`).toBeGreaterThanOrEqual(AA_TEXT);
		}
	});

	it.each(ALL)("keeps 600 identifiable as a graphic on the pale end - $name", (preset) => {
		// The non-text bar, for a border, a chart series or an icon - which is what
		// the middle of a ramp is actually reached for. 600 is the darkest step
		// that is NOT already covered by the text rule above.
		for (const background of [50, 100]) {
			const ratio = reportRatio(contrastOfRgb(ramp(preset.name, 600)!, ramp(preset.name, background)!));
			expect(ratio, `600 on ${background}`).toBeGreaterThanOrEqual(NON_TEXT);
		}
	});
});

/**
 * Not an assertion - a printout.
 *
 * The instruction that produced this slice was "report what you measured, not
 * that it looks right". A suite that only says PASS has measured 224 pairings
 * and told nobody a single number, so the worst row of every palette is printed
 * on every run. When one of them starts creeping towards 7.0, that is visible
 * long before it crosses.
 */
describe("measured", () => {
	it("prints the worst pairing of every preset in both themes", () => {
		const lines: string[] = [];

		for (const preset of PALETTE_PRESETS) {
			for (const theme of ["light", "dark"] as const) {
				const rows = measurePairings(resolverFor(tokensFor(preset.name, theme)));
				const text = rows.filter((row) => row.kind === "text");
				const nonText = rows.filter((row) => row.kind === "non-text");
				const worstText = text.reduce((low, row) => (row.ratio < low.ratio ? row : low), text[0]);
				const worstNonText = nonText.reduce((low, row) => (row.ratio < low.ratio ? row : low), nonText[0]);

				lines.push(
					`${preset.name.padEnd(8)} ${theme.padEnd(5)} text ${worstText.ratio.toFixed(2)}:1 (${worstText.id})` +
						`  non-text ${worstNonText.ratio.toFixed(2)}:1 (${worstNonText.id})`,
				);
			}
		}

		console.info(`\nworst pairing per preset, measured from the shipped stylesheet:\n${lines.join("\n")}\n`);
		expect(lines).toHaveLength(PALETTE_PRESETS.length * 2);
	});
});

describe("the arithmetic itself", () => {
	// The measurements above are only worth as much as this is. Three anchors
	// with hand-checkable answers: if the conversion drifts, every ratio in the
	// suite drifts with it and every assertion still passes.
	const white: Rgb = { b: 255, g: 255, r: 255 };
	const black: Rgb = { b: 0, g: 0, r: 0 };

	it("puts black on white at 21:1", () => {
		expect(reportRatio(contrastOfRgb(black, white))).toBe(21);
	});

	it("converts oklch to the sRGB primaries", () => {
		// oklch(0.628 0.2577 29.23) is pure sRGB red, per the CSS Color 4 spec's
		// own worked example.
		const red = parseOklch("oklch(0.628 0.2577 29.23)");
		expect(red).not.toBeNull();

		const rgb = oklchToRgb(red as never);
		expect(rgb.r).toBeGreaterThan(250);
		expect(rgb.g).toBeLessThan(6);
		expect(rgb.b).toBeLessThan(6);
	});

	it("knows an unpaintable chroma when it sees one", () => {
		// A very light, very saturated blue: legal CSS, no sRGB pixel behind it.
		expect(isInGamut({ c: 0.3, h: 250, l: 0.85 })).toBe(false);
		expect(isInGamut({ c: 0.05, h: 250, l: 0.85 })).toBe(true);
	});

	it("rounds a ratio down, never up", () => {
		// 6.999 must not print as 7.00 on a page whose whole job is that number.
		expect(reportRatio(6.999)).toBe(6.99);
		expect(AA_TEXT).toBe(4.5);
	});
});

/**
 * Designer palettes, which are measured rather than gated.
 *
 * The one thing this CAN assert is the one thing the feature promises: every
 * value a designer supplied reaches the stylesheet unchanged. A future
 * "helpful" clamp in the generator would turn the report green and the brand
 * wrong, and this is what notices.
 */
// `describe.each` throws on an empty array, and a repo with no designer palette
// committed is a perfectly normal state - the unit suite next door covers the
// behaviour either way.
describe.skipIf(DESIGNER.length === 0).each(DESIGNER)("$name - supplied by a designer", (preset) => {
	const tokens = tokensFor(preset.name, "light");
	const supplied = preset.supplied!;

	// Which token each of the five lands in. Kept here rather than imported so a
	// change to the mapping has to be acknowledged in a test rather than followed.
	const MAPPING: [keyof typeof supplied, string][] = [
		["background", "--background"],
		["foreground", "--foreground"],
		["brand", "--brand-primary"],
		["brand", "--gradient-brand-via"],
		["secondary", "--brand-secondary"],
		// The accent lands on the status rail, not the brand gradient - see the note
		// in applySupplied about which role paints what.
		["accent", "--rail-accent-tint"],
	];

	it.each(MAPPING)("ships the supplied %s verbatim", (role, token) => {
		const given = supplied[role];
		// secondary and accent are optional - absent means derived, and a derived
		// value is not a broken promise, it is the promise this file never made.
		if (!given) return;

		const shipped = parseOklch(tokens[token] ?? "");
		expect(shipped, `${token} resolves`).not.toBeNull();
		expect(oklchToHex(shipped!), `${token} is what the designer gave`).toBe(given.toLowerCase());
	});

	/*
	 * THE DIVISION OF RESPONSIBILITY, as an assertion.
	 *
	 * A designer palette is anchored to ONE theme. That theme ships the hex
	 * verbatim and may sit below any bar - the tests above pin that, and it is the
	 * designer's own colour to answer for. The OTHER theme is not theirs: it is
	 * derived, entirely by this generator, from a hue and a chroma. Nobody handed
	 * it over and nobody can be overruled by fixing it, so it has no excuse for
	 * being less than AAA.
	 *
	 * That is the whole contract this file exists to hold: **your hex is your
	 * obligation in the theme you chose; the sibling is ours, and ours passes.**
	 *
	 * Two bars, because a brand fill has two jobs. It carries a label (7:1, text)
	 * and it has to be findable against the surface behind it (3:1, SC 1.4.11 -
	 * a fill is a graphic, not type). Measured against `--surface-secondary`, the
	 * lightest ground a brand control lands on: clearing the page and failing the
	 * nested panel is the exact bug that started this, and the page is the easier
	 * of the two.
	 */
	it("derives a sibling that clears AAA in the theme the designer did not choose", () => {
		const derivedTheme = preset.brandTheme === "dark" ? "light" : "dark";
		const derived = tokensFor(preset.name, derivedTheme);

		const fill = parseOklch(derived["--gradient-brand-via"] ?? "");
		const ink = parseOklch(derived["--gradient-brand-foreground"] ?? "");
		const ground = parseOklch(derived["--surface-secondary"] ?? derived["--background"] ?? "");

		expect(fill, "the derived fill resolves").not.toBeNull();
		expect(ink, "its paired ink resolves").not.toBeNull();
		expect(ground, "the ground it sits on resolves").not.toBeNull();

		const onInk = reportRatio(contrastOfRgb(oklchToRgb(ink!), oklchToRgb(fill!)));
		const onGround = reportRatio(contrastOfRgb(oklchToRgb(fill!), oklchToRgb(ground!)));

		expect(onInk, `${preset.name}/${derivedTheme}: label on the derived fill`).toBeGreaterThanOrEqual(AAA_TEXT);
		expect(onGround, `${preset.name}/${derivedTheme}: derived fill against its ground`).toBeGreaterThanOrEqual(
			NON_TEXT,
		);
	});

	it("still fills the roles it was not given", () => {
		// The other half: an absent role must be DERIVED, not missing. A token that
		// resolves to nothing is a component with no colour at all.
		for (const [, token] of MAPPING) {
			expect(parseOklch(tokens[token] ?? ""), `${token} resolves`).not.toBeNull();
		}
	});

	it("still solves an ink for every supplied fill", () => {
		// Not held to AAA - held to existing and being legible at all. A supplied
		// fill with no ink is the failure mode that would ship an invisible label.
		for (const [fill, ink] of [
			["--brand-primary", "--brand-primary-foreground"],
			["--brand-secondary", "--brand-secondary-foreground"],
			["--gradient-brand-via", "--gradient-brand-foreground"],
		]) {
			const fillColor = parseOklch(tokens[fill] ?? "");
			const inkColor = parseOklch(tokens[ink] ?? "");
			expect(inkColor, `${ink} exists`).not.toBeNull();

			const ratio = contrastOfRgb(oklchToRgb(inkColor!), oklchToRgb(fillColor!));
			expect(reportRatio(ratio), `${ink} on ${fill}`).toBeGreaterThanOrEqual(AA_TEXT);
		}
	});

	it("keeps every value it emits inside the sRGB gamut", () => {
		// The supplied five arrive from sRGB and cannot fail this. The derived
		// seventy can, and a designer palette does not exempt them.
		for (const [token, value] of Object.entries(tokens)) {
			const color = parseOklch(value);
			if (color) expect(isInGamut(color), `${token} is ${value}`).toBe(true);
		}
	});
});
